output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elastichal:9200}'
  username: '${ELASTICSEARCH_USERNAME:elastic}'
  password: '${ELASTICSEARCH_PASSWORD:MonMdp}'
  
- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    #- index_recovery
    #- index_summary
    - shard
    #- ml_job
  period: 10s
  hosts: ["http://elastichal:9200"]
  username: "elastic"
  password: "MonMdp"
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  #index_recovery.active_only: true
  xpack.enabled: false
  #scope: node
 
