metricbeat.modules:
- module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s

  # Nginx hosts
  hosts: ["http://sovisu.univ-tln.fr"]

  # Path to server status. Default nginx_status
  server_status_path: "etat"
  
 