# Generated by Django 3.1.5 on 2022-04-18 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elasticHal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elastichal",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="elastichal",
            name="name",
        ),
    ]
