# Generated by Django 3.1.5 on 2022-04-18 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elasticHal", "0003_elastichal_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Elastichal",
            new_name="Elastichal_csv",
        ),
    ]
