# Generated by Django 3.1.5 on 2022-04-18 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elasticHal", "0004_auto_20220418_1814"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Elastichal_csv",
            new_name="ElastichalCsv",
        ),
    ]
