# Generated by Django 3.1.5 on 2022-04-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticHal', '0006_auto_20220418_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name_plural': 'Laboratories'},
        ),
    ]
