# Generated by Django 4.0.6 on 2022-10-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticHal', '0009_auto_20220419_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name': 'Laboratoire', 'verbose_name_plural': 'Laboratoires'},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'verbose_name': 'Chercheur', 'verbose_name_plural': 'Chercheurs'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
