---
version: "3.8"
services:
  redis:
    image: "redis:alpine"

    command: redis-server #--requirepass MonMdp

    ports:
     - "6379:6379"

    volumes:
     - ./redis/redis-data:/var/lib/redis
     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

    networks:
      - elk


  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION:-8.3.2}
    # https://github.com/docker/swarmkit/issues/1951
    hostname: "metricbeathal"
    user: root
    networks:
      - elk
    volumes:
      #- /proc:/hostfs/proc:ro
      #- /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      #- /:/hostfs:ro
      #- /var/run/docker.sock:/var/run/docker.sock
      - /d/AnacondaProjects/SoVisu/doc/VisuStack/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - metricbeatvolum:/usr/share/metricbeat/data
      - /d/AnacondaProjects/SoVisu/doc/VisuStack/metricbeat/modules.d/:/usr/share/metricbeat/modules.d/
    environment:
      - ELASTICSEARCH_HOST=elastichal1
      - KIBANA_HOST=kibanahal
      - ELASTICSEARCH_USERNAME=david
      - ELASTICSEARCH_PASSWORD=MonMdp
    # disable strict permission checks
    command: ["--strict.perms=false"] #, "-system.hostfs=/hostfs"]
    links:
      - elastichal1
      - elastichal2
      - kibanahal

  elastichal1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: elastichal1

    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elastichal1
      - node.roles=master,data,remote_cluster_client
      #- node.data=true
      - cluster.name=sovisucluster
      #- cluster.name=sovisucluster
      - discovery.seed_hosts=elastichal2:9300,elastichal3:9302
      #- cluster.initial_master_nodes=elastichal1, elastichal2 #Pour le premier lancement seulement
      - "path.repo=/usr/share/elasticsearch/backup"
      - cluster.routing.allocation.enable=all
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - http.max_content_length=10MB
      #- "discovery.type=single-node"
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=false
      - ELASTIC_USERNAME=david
      - ELASTIC_PASSWORD=MonMdp
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    networks:
      - elk
    volumes:
      - es-data1:/usr/share/elasticsearch/data
      - es-backup1:/usr/share/elasticsearch/backup

  elastichal2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: elastichal2

    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - node.name=elastichal2
      - node.roles=master,data,remote_cluster_client
      #- node.data=true
      - cluster.name=sovisucluster
      - discovery.seed_hosts=elastichal1:9300
      #- discovery.seed_providers=elastichal1:9300
      - cluster.initial_master_nodes=elastichal1, elastichal2 #Pour le premier lancement seulement
      - "path.repo=/usr/share/elasticsearch/backup"
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - http.max_content_length=10MB
      #- "discovery.type=single-node"
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=false
      - ELASTIC_USERNAME=david
      - ELASTIC_PASSWORD=MonMdp
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    depends_on:
      - elastichal1
    links:
      - elastichal1
      - elastichal3
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk
    volumes:
      - es-data2:/usr/share/elasticsearch/data
      - es-backup1:/usr/share/elasticsearch/backup

  elastichal3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: elastichal3

    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      - node.name=elastichal3
      - node.roles=data,remote_cluster_client
      #- node.data=true
      - cluster.name=sovisucluster
      - discovery.seed_hosts=elastichal1:9300,elastichal2:9301
      #- discovery.seed_providers=elastichal1:9300
      #- cluster.initial_master_nodes=elastichal1, elastichal2 #Pour le premier lancement seulement
      - "path.repo=/usr/share/elasticsearch/backup"
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - http.max_content_length=10MB
      #- "discovery.type=single-node"
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=false
      - ELASTIC_USERNAME=david
      - ELASTIC_PASSWORD=MonMdp
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    depends_on:
      - elastichal1
    links:
      - elastichal1

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk
    volumes:
      - es-data3:/usr/share/elasticsearch/data
      - es-backup1:/usr/share/elasticsearch/backup

  kibanahal:
    image: docker.elastic.co/kibana/kibana:8.3.2
    container_name: kibanahal

    ports:
      - "5601:5601"
    depends_on:
      - elastichal1
      - elastichal2
      - elastichal3
    links:
      - elastichal1
      - elastichal2
      - elastichal3
    volumes:
      - /d/AnacondaProjects/SoVisu/doc/VisuStack/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      KIBANA_USERNAME: david_system
      KIBANA_PASSWORD: MonMdp
      ELASTICSEARCH_PASSWORD: MonMdp
      ELASTICSEARCH_USERNAME: david
      #ELASTICSEARCH_HOST_PORT: "http://elastichal:9200"
    networks:
      - elk
     
volumes:
  es-data1:
     driver: local
     driver_opts:
        o: bind
        type: none
        device: "/d/AnacondaProjects/SoVisu/doc/VisuStack/volume/data1" # /d/AnacondaProjects/SoVisu/doc/VisuStack/

  es-backup1:
     driver: local
     driver_opts:
        o: bind
        type: none
        device: "/d/AnacondaProjects/SoVisu/doc/VisuStack/volume/backup1"

  es-data2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/d/AnacondaProjects/SoVisu/doc/VisuStack/volume/data2"

  es-data3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/d/AnacondaProjects/SoVisu/doc/VisuStack/volume/data"

  metricbeatvolum:
     driver: local
     driver_opts:
        o: bind
        type: none
        device: "/d/AnacondaProjects/SoVisu/doc/VisuStack/volume/MB-data"

networks:
  elk:
    driver: bridge
    
