- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    #- index_recovery
    #- index_summary
    - shard
    #- ml_job
  period: 10s
  hosts: ["http://elastichal1:9200", "http://elastichal2:9200"]
  username: "david"
  password: "MonMdp"
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  #index_recovery.active_only: true
  xpack.enabled: false
  #scope: node
 